language: go

go:
  - "1.11.x"

cache:
  directories:
    - ${GOPATH}/pkg/dep
    - ${TRAVIS_BUILD_DIR}/cache

before_install:
  - sudo apt-get update -qq && sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -qq
  - ${TRAVIS_HOME}/gopath/src/github.com/medibloc/go-medibloc/script/travis-rocksdb.sh
  - go get github.com/golang/dep/cmd/dep

install:
  - cd ${TRAVIS_HOME}/gopath/src/github.com/medibloc/go-medibloc
  - make dep

script:
  - go test -race -coverprofile=coverage.txt -coverpkg=./... -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
