language: go

go:
  - "1.11.x"

cache:
  directories:
    - ${GOPATH}/pkg/dep
    - ${TRAVIS_BUILD_DIR}/cache/rocksdb/v5.15.10

before_install:
  - sudo apt-get update -qq && sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -qq
  - ${TRAVIS_HOME}/gopath/src/github.com/medibloc/go-medibloc/script/travis-rocksdb.sh
  - sudo cp -r --preserve=links ${TRAVIS_BUILD_DIR}/cache/rocksdb/v5.15.10/lib/librocksdb.* /usr/lib/
  - sudo cp -r ${TRAVIS_BUILD_DIR}/cache/rocksdb/v5.15.10/include/* /usr/include/
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint

install:
  - cd ${TRAVIS_HOME}/gopath/src/github.com/medibloc/go-medibloc
  - make dep

script:
  - go test -race -coverprofile=coverage.txt -coverpkg=./... -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
