language: go

go:
  - "1.11.x"

before_install:
  - sudo apt-get update -qq && sudo apt-get install libsnappy-dev zlib1g-dev libbz2-dev -qq
  - git clone https://github.com/facebook/rocksdb.git ${TRAVIS_HOME}
  - cd ${TRAVIS_HOME}/rocksdb
  - make shared_lib
  - sudo cp --preserve=links ./librocksdb.* /usr/lib/
  - sudo cp -r ./include/rocksdb/ /usr/include/
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls

install:
  - cd ${TRAVIS_HOME}/gopath/src/github.com/medibloc/go-medibloc
  - make dep

script:
  - go test -race -coverprofile=coverage.txt -coverpkg=./... -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
